### ISSUE TITLE
recursive calls

### ISSUE THREAD

**Issue by Kevin-Hamilton** [pmndrs/rafz#4]
I'm wondering what the reason is for this:

- Recursive calls (ie: raf in raf) are flushed in the same frame.

There are some use-case examples where you might want to schedule an update on the frame after the next frame. See e.g. https://youtu.be/cCOL7MC4Pl0?t=1228

I've mocked this up here: https://codesandbox.io/s/busy-kare-bvpej

You can kind of hack around this by using raf.setTimeout  but that's not even guaranteed to hit the frame after this frame, unless you use a high enough value for the timeout.  For instance, I tried this with a timeout of 10 and I would get variable behavior - some clicks would fire the css mutation in the same frame, some in the following frame.

**Comment by aleclarson** [comment]
Released in v0.1.13
